#pragma once

// Player Constants
const float DEFAULT_PLAYER_MOVEMENT_SPEED = 5.0f;
const float DEFAULT_PLAYER_HEALTH = 100;

// Weapon Constants
const int DEFAULT_WEAPON_AMMO_CAPACITY = 100;
const int DEFAULT_WEAPON_AMMUNITION = 40;
const int DEFAULT_WEAPON_RELOAD_CAPACITY = 40;
const int DEFAULT_WEAPON_DAMAGE = 10;

const float DEFAULT_WEAPON_RELOAD_SPEED = 2.0f;
const float DEFAULT_WEAPON_FIRING_DELAY = 0.5f;